# Auto-generated Terraform — rupam-test-server
# Generated by AI Infrastructure Agent

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }

  backend "s3" {
    bucket         = "rupam-test-server-tf-state"
    key            = "rupam-test-server/terraform.tfstate"
    region         = "ap-south-1"
    dynamodb_table = "rupam-test-server-tf-lock"
  }
}

provider "aws" {
  region = "ap-south-1"

  default_tags {
    tags = {
      Project   = "rupam-test-server"
      ManagedBy = "terraform"
    }
  }
}




# ── EC2 ───────────────────────────────────────────────────────────
resource "aws_instance" "app" {
  ami           = "ami-0f58b397bc5c1f2e8"  # Amazon Linux 2 — Mumbai
  instance_type = ""

  

  tags = { Name = "rupam-test-server-server" }
}

output "ec2_public_ip" {
  value       = aws_instance.app.public_ip
  description = "Public IP of the EC2 instance"
}












